### PR TITLE
Update Jobflow example

### PR DESCRIPTION
**Pull request by JaGeo**
@QuantumChemist I am implementing some updates in the next days. 

I would also like to check if we can simplify the code if we swtich from `Atoms` to `MSONAtoms` in the functions.

### CODE REVIEW

**Comment by QuantumChemist** [comment]
Okidoki, let me know if I can help somehow. :)

**Comment by JaGeo** [comment]
I will likely ask you for further feedback and ideas. 😀

**Comment by JaGeo** [comment]
@jan-janssen I also tried to make the structures JSON serializable. One just needs to use `MSONAtoms(atom_object)` as a converter.

Once we have all contributions, we might want to see again how to move forward with regard to a potential publication.

**Comment by jan-janssen** [comment]
> @jan-janssen I also tried to make the structures JSON serializable. One just needs to use `MSONAtoms(atom_object)` as a converter.

I agree, while we do not want to define a "Standard", still including the recommendation to choose data types which are JSON-able makes a lot of sense.  

> Once we have all contributions, we might want to see again how to move forward with regard to a potential publication.

I still try to reach @mbercx

**Pull request merged**
